// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetUsers() {
  return window['go']['main']['App']['GetUsers']();
}

export function PickWinner(arg1) {
  return window['go']['main']['App']['PickWinner'](arg1);
}

export function ShoutWinner(arg1) {
  return window['go']['main']['App']['ShoutWinner'](arg1);
}

export function UpdateUsers() {
  return window['go']['main']['App']['UpdateUsers']();
}
