// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLog(arg1) {
  return window['go']['main']['App']['AddLog'](arg1);
}

export function ExecuteExit() {
  return window['go']['main']['App']['ExecuteExit']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetScheduleStatus() {
  return window['go']['main']['App']['GetScheduleStatus']();
}

export function SetSchedule(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetSchedule'](arg1, arg2, arg3);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}
