// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddLog(arg1:string):Promise<void>;

export function ExecuteExit():Promise<void>;

export function GetLogs():Promise<Array<string>>;

export function GetScheduleStatus():Promise<main.ScheduleStatus>;

export function SetSchedule(arg1:number,arg2:number,arg3:boolean):Promise<void>;

export function ShowWindow():Promise<void>;
