// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBan(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddBan'](arg1, arg2, arg3);
}

export function AddLog(arg1) {
  return window['go']['main']['App']['AddLog'](arg1);
}

export function AddPayout(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddPayout'](arg1, arg2, arg3);
}

export function AddStockedItem(arg1, arg2) {
  return window['go']['main']['App']['AddStockedItem'](arg1, arg2);
}

export function BanPlayer(arg1, arg2, arg3) {
  return window['go']['main']['App']['BanPlayer'](arg1, arg2, arg3);
}

export function CheckAddPayout(arg1, arg2, arg3) {
  return window['go']['main']['App']['CheckAddPayout'](arg1, arg2, arg3);
}

export function ClearBan(arg1) {
  return window['go']['main']['App']['ClearBan'](arg1);
}

export function ClearCompleted() {
  return window['go']['main']['App']['ClearCompleted']();
}

export function DeletePayout(arg1) {
  return window['go']['main']['App']['DeletePayout'](arg1);
}

export function DeleteStockedItem(arg1) {
  return window['go']['main']['App']['DeleteStockedItem'](arg1);
}

export function GetActiveStockedItemNames() {
  return window['go']['main']['App']['GetActiveStockedItemNames']();
}

export function GetActiveStockedItems() {
  return window['go']['main']['App']['GetActiveStockedItems']();
}

export function GetBanList() {
  return window['go']['main']['App']['GetBanList']();
}

export function GetDailyGBOut() {
  return window['go']['main']['App']['GetDailyGBOut']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetPayouts() {
  return window['go']['main']['App']['GetPayouts']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSkipStripScan() {
  return window['go']['main']['App']['GetSkipStripScan']();
}

export function GetStockedItems() {
  return window['go']['main']['App']['GetStockedItems']();
}

export function GetTradeInfo() {
  return window['go']['main']['App']['GetTradeInfo']();
}

export function RefreshInventory() {
  return window['go']['main']['App']['RefreshInventory']();
}

export function RefreshQueue() {
  return window['go']['main']['App']['RefreshQueue']();
}

export function ReloadBans() {
  return window['go']['main']['App']['ReloadBans']();
}

export function RemoveBan(arg1) {
  return window['go']['main']['App']['RemoveBan'](arg1);
}

export function ReturnAllToOwner(arg1) {
  return window['go']['main']['App']['ReturnAllToOwner'](arg1);
}

export function SaveSettings(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2, arg3);
}

export function SetSkipStripScan(arg1) {
  return window['go']['main']['App']['SetSkipStripScan'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function TogglePayoutStatus(arg1) {
  return window['go']['main']['App']['TogglePayoutStatus'](arg1);
}

export function ToggleStockedItem(arg1) {
  return window['go']['main']['App']['ToggleStockedItem'](arg1);
}
