// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLog(arg1) {
  return window['go']['main']['App']['AddLog'](arg1);
}

export function AddPayout(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddPayout'](arg1, arg2, arg3);
}

export function ClearCompleted() {
  return window['go']['main']['App']['ClearCompleted']();
}

export function DeletePayout(arg1) {
  return window['go']['main']['App']['DeletePayout'](arg1);
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetPayouts() {
  return window['go']['main']['App']['GetPayouts']();
}

export function RefreshInventory() {
  return window['go']['main']['App']['RefreshInventory']();
}

export function RefreshQueue() {
  return window['go']['main']['App']['RefreshQueue']();
}

export function ReturnAllToOwner(arg1) {
  return window['go']['main']['App']['ReturnAllToOwner'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function TogglePayoutStatus(arg1) {
  return window['go']['main']['App']['TogglePayoutStatus'](arg1);
}
