// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetConfig():Promise<main.WaveConfig>;

export function SendWaveNow():Promise<main.WaveConfig>;

export function SetConfig(arg1:number,arg2:boolean):Promise<main.WaveConfig>;

export function ToggleWave():Promise<main.WaveConfig>;
