// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetBlockedPlayers():Promise<Array<string>>;

export function GetDbStatus():Promise<string>;

export function GetPlayers():Promise<Array<string>>;

export function GetStats():Promise<main.CasinoStats>;

export function ToggleBlockPlayer(arg1:string):Promise<void>;
