// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBlockedPlayers() {
  return window['go']['main']['App']['GetBlockedPlayers']();
}

export function GetDbStatus() {
  return window['go']['main']['App']['GetDbStatus']();
}

export function GetPlayerStats() {
  return window['go']['main']['App']['GetPlayerStats']();
}

export function GetPlayers() {
  return window['go']['main']['App']['GetPlayers']();
}

export function GetSettings(arg1) {
  return window['go']['main']['App']['GetSettings'](arg1);
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function SaveSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2);
}

export function ToggleBlockPlayer(arg1) {
  return window['go']['main']['App']['ToggleBlockPlayer'](arg1);
}
