// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetBlockedPlayers():Promise<Array<string>>;

export function GetDbStatus():Promise<string>;

export function GetOwnerKey():Promise<string>;

export function GetPlayerGameStats(arg1:string,arg2:string,arg3:string):Promise<Array<main.GameStats>>;

export function GetPlayerStats(arg1:string,arg2:string):Promise<Array<main.PlayerStats>>;

export function GetPlayers():Promise<Array<string>>;

export function GetSettings(arg1:string):Promise<string>;

export function GetStats(arg1:string,arg2:string):Promise<main.CasinoStats>;

export function SaveSettings(arg1:string,arg2:string):Promise<void>;

export function ToggleBlockPlayer(arg1:string):Promise<void>;
