// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBlockedPlayers() {
  return window['go']['main']['App']['GetBlockedPlayers']();
}

export function GetDbStatus() {
  return window['go']['main']['App']['GetDbStatus']();
}

export function GetLedgerStats(arg1, arg2) {
  return window['go']['main']['App']['GetLedgerStats'](arg1, arg2);
}

export function GetOwnerKey() {
  return window['go']['main']['App']['GetOwnerKey']();
}

export function GetPlayerGameStats(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetPlayerGameStats'](arg1, arg2, arg3);
}

export function GetPlayerStats(arg1, arg2) {
  return window['go']['main']['App']['GetPlayerStats'](arg1, arg2);
}

export function GetPlayers() {
  return window['go']['main']['App']['GetPlayers']();
}

export function GetSettings(arg1) {
  return window['go']['main']['App']['GetSettings'](arg1);
}

export function GetStats(arg1, arg2) {
  return window['go']['main']['App']['GetStats'](arg1, arg2);
}

export function SaveSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2);
}

export function ToggleBlockPlayer(arg1) {
  return window['go']['main']['App']['ToggleBlockPlayer'](arg1);
}
