// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBlockedPlayers() {
  return window['go']['main']['App']['GetBlockedPlayers']();
}

export function GetDbStatus() {
  return window['go']['main']['App']['GetDbStatus']();
}

export function GetPlayers() {
  return window['go']['main']['App']['GetPlayers']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function ToggleBlockPlayer(arg1) {
  return window['go']['main']['App']['ToggleBlockPlayer'](arg1);
}
