// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearSessions() {
  return window['go']['main']['App']['ClearSessions']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function StartTracking() {
  return window['go']['main']['App']['StartTracking']();
}

export function StopTracking() {
  return window['go']['main']['App']['StopTracking']();
}
