// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearDebugSnapshot() {
  return window['go']['main']['App']['ClearDebugSnapshot']();
}

export function ClearSessions() {
  return window['go']['main']['App']['ClearSessions']();
}

export function CreateRaffle(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['CreateRaffle'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function DrawWinnerForCurrentSession() {
  return window['go']['main']['App']['DrawWinnerForCurrentSession']();
}

export function GetDebugSnapshot() {
  return window['go']['main']['App']['GetDebugSnapshot']();
}

export function GetSessionTally(arg1) {
  return window['go']['main']['App']['GetSessionTally'](arg1);
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function GetTicketAnnounceEnabled() {
  return window['go']['main']['App']['GetTicketAnnounceEnabled']();
}

export function GetTicketProgressEnabled() {
  return window['go']['main']['App']['GetTicketProgressEnabled']();
}

export function PostOrUpdateRaffleWebhook() {
  return window['go']['main']['App']['PostOrUpdateRaffleWebhook']();
}

export function PostWinnerProofForCurrentSession(arg1, arg2) {
  return window['go']['main']['App']['PostWinnerProofForCurrentSession'](arg1, arg2);
}

export function PostWinnerProofForSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['PostWinnerProofForSession'](arg1, arg2, arg3);
}

export function RemoveParticipantFromCurrentSession(arg1) {
  return window['go']['main']['App']['RemoveParticipantFromCurrentSession'](arg1);
}

export function RepostRaffleWebhook() {
  return window['go']['main']['App']['RepostRaffleWebhook']();
}

export function ResumeSession(arg1) {
  return window['go']['main']['App']['ResumeSession'](arg1);
}

export function SetAutoMsgConfig(arg1, arg2) {
  return window['go']['main']['App']['SetAutoMsgConfig'](arg1, arg2);
}

export function SetBonusEvery(arg1) {
  return window['go']['main']['App']['SetBonusEvery'](arg1);
}

export function SetEnabled(arg1) {
  return window['go']['main']['App']['SetEnabled'](arg1);
}

export function SetHypeShoutConfig(arg1, arg2) {
  return window['go']['main']['App']['SetHypeShoutConfig'](arg1, arg2);
}

export function SetJoinShoutConfig(arg1, arg2) {
  return window['go']['main']['App']['SetJoinShoutConfig'](arg1, arg2);
}

export function SetRaffleDiscordConfig(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SetRaffleDiscordConfig'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SetRaffleSponsorConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetRaffleSponsorConfig'](arg1, arg2, arg3);
}

export function SetTicketAnnounceEnabled(arg1) {
  return window['go']['main']['App']['SetTicketAnnounceEnabled'](arg1);
}

export function SetTicketProgressEnabled(arg1) {
  return window['go']['main']['App']['SetTicketProgressEnabled'](arg1);
}

export function StartRaffle() {
  return window['go']['main']['App']['StartRaffle']();
}

export function StartRaffleWithWindow(arg1, arg2) {
  return window['go']['main']['App']['StartRaffleWithWindow'](arg1, arg2);
}

export function StopRaffle() {
  return window['go']['main']['App']['StopRaffle']();
}

export function ToggleAutoMsg(arg1) {
  return window['go']['main']['App']['ToggleAutoMsg'](arg1);
}

export function ToggleHypeShout(arg1) {
  return window['go']['main']['App']['ToggleHypeShout'](arg1);
}

export function ToggleJoinShout(arg1) {
  return window['go']['main']['App']['ToggleJoinShout'](arg1);
}

export function UpsertManualParticipant(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpsertManualParticipant'](arg1, arg2, arg3);
}
