// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearDebugSnapshot():Promise<void>;

export function ClearSessions():Promise<main.RaffleState>;

export function CreateRaffle(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string,arg6:string,arg7:string):Promise<main.RaffleState>;

export function DeleteSession(arg1:number):Promise<main.RaffleState>;

export function DrawWinnerForCurrentSession():Promise<string>;

export function GetDebugSnapshot():Promise<string>;

export function GetSessionTally(arg1:number):Promise<main.SessionTally>;

export function GetState():Promise<main.RaffleState>;

export function GetTicketAnnounceEnabled():Promise<boolean>;

export function GetTicketProgressEnabled():Promise<boolean>;

export function PostOrUpdateRaffleWebhook():Promise<string>;

export function PostWinnerProofForCurrentSession(arg1:string,arg2:string):Promise<string>;

export function PostWinnerProofForSession(arg1:number,arg2:string,arg3:string):Promise<string>;

export function RemoveParticipantFromCurrentSession(arg1:string):Promise<main.RaffleState>;

export function RepostRaffleWebhook():Promise<string>;

export function ResumeSession(arg1:number):Promise<main.RaffleState>;

export function SetBonusEvery(arg1:number):Promise<main.RaffleState>;

export function SetEnabled(arg1:boolean):Promise<main.RaffleState>;

export function SetHypeShoutConfig(arg1:string,arg2:number):Promise<main.RaffleState>;

export function SetRaffleDiscordConfig(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string,arg6:boolean):Promise<main.RaffleState>;

export function SetRaffleSponsorConfig(arg1:boolean,arg2:string,arg3:string):Promise<main.RaffleState>;

export function SetTicketAnnounceEnabled(arg1:boolean):Promise<main.RaffleState>;

export function SetTicketProgressEnabled(arg1:boolean):Promise<main.RaffleState>;

export function StartRaffle():Promise<main.RaffleState>;

export function StartRaffleWithWindow(arg1:string,arg2:string):Promise<main.RaffleState>;

export function StopRaffle():Promise<main.RaffleState>;

export function ToggleHypeShout(arg1:boolean):Promise<main.RaffleState>;

export function UpsertManualParticipant(arg1:string,arg2:number,arg3:number):Promise<main.RaffleState>;
