// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearSessions():Promise<main.RaffleState>;

export function GetState():Promise<main.RaffleState>;

export function SetBonusEvery(arg1:number):Promise<main.RaffleState>;

export function SetEnabled(arg1:boolean):Promise<main.RaffleState>;

export function StartRaffle():Promise<main.RaffleState>;

export function StartRaffleWithWindow(arg1:string,arg2:string):Promise<main.RaffleState>;

export function StopRaffle():Promise<main.RaffleState>;
