// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearDebugSnapshot() {
  return window['go']['main']['App']['ClearDebugSnapshot']();
}

export function ClearSessions() {
  return window['go']['main']['App']['ClearSessions']();
}

export function GetDebugSnapshot() {
  return window['go']['main']['App']['GetDebugSnapshot']();
}

export function GetSessionTally(arg1) {
  return window['go']['main']['App']['GetSessionTally'](arg1);
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function GetTicketAnnounceEnabled() {
  return window['go']['main']['App']['GetTicketAnnounceEnabled']();
}

export function ResumeSession(arg1) {
  return window['go']['main']['App']['ResumeSession'](arg1);
}

export function SetBonusEvery(arg1) {
  return window['go']['main']['App']['SetBonusEvery'](arg1);
}

export function SetEnabled(arg1) {
  return window['go']['main']['App']['SetEnabled'](arg1);
}

export function SetTicketAnnounceEnabled(arg1) {
  return window['go']['main']['App']['SetTicketAnnounceEnabled'](arg1);
}

export function StartRaffle() {
  return window['go']['main']['App']['StartRaffle']();
}

export function StartRaffleWithWindow(arg1, arg2) {
  return window['go']['main']['App']['StartRaffleWithWindow'](arg1, arg2);
}

export function StopRaffle() {
  return window['go']['main']['App']['StopRaffle']();
}
