// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearSessions():Promise<main.TrackerState>;

export function GetState():Promise<main.TrackerState>;

export function StartTracking():Promise<main.TrackerState>;

export function StopTracking():Promise<main.TrackerState>;
