// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BuildAll():Promise<string>;

export function BuildSingle(arg1:string):Promise<string>;

export function CreateMissingTables():Promise<string>;

export function GetApps():Promise<Array<main.LaunchAppItem>>;

export function GetBuildTargets():Promise<Array<Record<string, string>>>;

export function GetGEarthStatus():Promise<main.GEarthStatus>;

export function GetStopChildrenOnExit():Promise<boolean>;

export function IsBuilding():Promise<boolean>;

export function KillAllTasks():Promise<string>;

export function KillApp(arg1:string):Promise<string>;

export function LaunchApp(arg1:string,arg2:string):Promise<string>;

export function LaunchGEarth():Promise<string>;

export function RefreshApps():Promise<Array<main.LaunchAppItem>>;

export function SetStopChildrenOnExit(arg1:boolean):Promise<void>;
