// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildAll() {
  return window['go']['main']['App']['BuildAll']();
}

export function BuildSingle(arg1) {
  return window['go']['main']['App']['BuildSingle'](arg1);
}

export function GetApps() {
  return window['go']['main']['App']['GetApps']();
}

export function GetBuildTargets() {
  return window['go']['main']['App']['GetBuildTargets']();
}

export function IsBuilding() {
  return window['go']['main']['App']['IsBuilding']();
}

export function LaunchApp(arg1) {
  return window['go']['main']['App']['LaunchApp'](arg1);
}

export function RefreshApps() {
  return window['go']['main']['App']['RefreshApps']();
}
