// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BlockPlayer(arg1) {
  return window['go']['main']['App']['BlockPlayer'](arg1);
}

export function GetBlockedPlayers() {
  return window['go']['main']['App']['GetBlockedPlayers']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function UnblockPlayer(arg1) {
  return window['go']['main']['App']['UnblockPlayer'](arg1);
}
