// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BlockPlayer(arg1:string):Promise<void>;

export function GetBlockedPlayers():Promise<Array<string>>;

export function GetStats():Promise<main.CasinoStats>;

export function UnblockPlayer(arg1:string):Promise<void>;
