// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetGEarthStatus():Promise<Record<string, any>>;

export function GetRoomUsers():Promise<Array<main.RoomUser>>;

export function Greet(arg1:string):Promise<string>;

export function RequestRoomUsers():Promise<void>;

export function ShowWindow():Promise<void>;
