// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGEarthStatus() {
  return window['go']['main']['App']['GetGEarthStatus']();
}

export function GetRoomUsers() {
  return window['go']['main']['App']['GetRoomUsers']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RequestRoomUsers() {
  return window['go']['main']['App']['RequestRoomUsers']();
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}
