// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddRoomRight(arg1:string):Promise<void>;

export function GetAutoGrantRights():Promise<boolean>;

export function GetGEarthStatus():Promise<Record<string, any>>;

export function GetRoomRights():Promise<Array<string>>;

export function GetRoomUsers():Promise<Array<main.RoomUser>>;

export function Greet(arg1:string):Promise<string>;

export function RemoveRoomRight(arg1:string):Promise<void>;

export function RequestRoomUsers():Promise<void>;

export function ShowWindow():Promise<void>;

export function ToggleAutoGrantRights(arg1:boolean):Promise<void>;
