// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddChatLog(arg1) {
  return window['go']['main']['App']['AddChatLog'](arg1);
}

export function AddDebugLog(arg1, arg2) {
  return window['go']['main']['App']['AddDebugLog'](arg1, arg2);
}

export function AddErrorLog(arg1, arg2) {
  return window['go']['main']['App']['AddErrorLog'](arg1, arg2);
}

export function AddLogMsg(arg1) {
  return window['go']['main']['App']['AddLogMsg'](arg1);
}

export function BuildCasinoStats(arg1) {
  return window['go']['main']['App']['BuildCasinoStats'](arg1);
}

export function ClearGameHistory() {
  return window['go']['main']['App']['ClearGameHistory']();
}

export function ClearTradeItems() {
  return window['go']['main']['App']['ClearTradeItems']();
}

export function GetAutoShoutConfig() {
  return window['go']['main']['App']['GetAutoShoutConfig']();
}

export function GetBlockFriendListUpdateConfig() {
  return window['go']['main']['App']['GetBlockFriendListUpdateConfig']();
}

export function GetBlockPollEventEligibilityOutgoingConfig() {
  return window['go']['main']['App']['GetBlockPollEventEligibilityOutgoingConfig']();
}

export function GetBlockRecommendedRoomsConfig() {
  return window['go']['main']['App']['GetBlockRecommendedRoomsConfig']();
}

export function GetBlockRecommendedRoomsOutgoingConfig() {
  return window['go']['main']['App']['GetBlockRecommendedRoomsOutgoingConfig']();
}

export function GetBlockRemoveBuddyConfig() {
  return window['go']['main']['App']['GetBlockRemoveBuddyConfig']();
}

export function GetBlockSlideObjectBundleConfig() {
  return window['go']['main']['App']['GetBlockSlideObjectBundleConfig']();
}

export function GetBlockSlideObjectBundleOutgoingConfig() {
  return window['go']['main']['App']['GetBlockSlideObjectBundleOutgoingConfig']();
}

export function GetBlockStatusEffectsConfig() {
  return window['go']['main']['App']['GetBlockStatusEffectsConfig']();
}

export function GetCasinoStatsJSON(arg1) {
  return window['go']['main']['App']['GetCasinoStatsJSON'](arg1);
}

export function GetCatalogItemValue(arg1) {
  return window['go']['main']['App']['GetCatalogItemValue'](arg1);
}

export function GetCatalogNameSet() {
  return window['go']['main']['App']['GetCatalogNameSet']();
}

export function GetCurrentTradeItems() {
  return window['go']['main']['App']['GetCurrentTradeItems']();
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function GetGameHistoryJSON() {
  return window['go']['main']['App']['GetGameHistoryJSON']();
}

export function GetLastTradePartnerName() {
  return window['go']['main']['App']['GetLastTradePartnerName']();
}

export function GetTradeItemsJSON() {
  return window['go']['main']['App']['GetTradeItemsJSON']();
}

export function LoadCatalog() {
  return window['go']['main']['App']['LoadCatalog']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function OpenLastTrade() {
  return window['go']['main']['App']['OpenLastTrade']();
}

export function PauseCasinoSetup() {
  return window['go']['main']['App']['PauseCasinoSetup']();
}

export function ResumeCasinoSetup() {
  return window['go']['main']['App']['ResumeCasinoSetup']();
}

export function SaveAutoShoutConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveAutoShoutConfig'](arg1, arg2);
}

export function SaveCatalog(arg1) {
  return window['go']['main']['App']['SaveCatalog'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ShowCommands() {
  return window['go']['main']['App']['ShowCommands']();
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function SkipDiceSetupForTesting() {
  return window['go']['main']['App']['SkipDiceSetupForTesting']();
}

export function StartCasinoSetup(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartCasinoSetup'](arg1, arg2, arg3, arg4);
}

export function StopCasinoSetup() {
  return window['go']['main']['App']['StopCasinoSetup']();
}

export function ToggleAutoShout(arg1) {
  return window['go']['main']['App']['ToggleAutoShout'](arg1);
}

export function ToggleBlockFriendListUpdate(arg1) {
  return window['go']['main']['App']['ToggleBlockFriendListUpdate'](arg1);
}

export function ToggleBlockPollEventEligibilityOutgoing(arg1) {
  return window['go']['main']['App']['ToggleBlockPollEventEligibilityOutgoing'](arg1);
}

export function ToggleBlockRecommendedRooms(arg1) {
  return window['go']['main']['App']['ToggleBlockRecommendedRooms'](arg1);
}

export function ToggleBlockRecommendedRoomsOutgoing(arg1) {
  return window['go']['main']['App']['ToggleBlockRecommendedRoomsOutgoing'](arg1);
}

export function ToggleBlockRemoveBuddy(arg1) {
  return window['go']['main']['App']['ToggleBlockRemoveBuddy'](arg1);
}

export function ToggleBlockSlideObjectBundle(arg1) {
  return window['go']['main']['App']['ToggleBlockSlideObjectBundle'](arg1);
}

export function ToggleBlockSlideObjectBundleOutgoing(arg1) {
  return window['go']['main']['App']['ToggleBlockSlideObjectBundleOutgoing'](arg1);
}

export function ToggleBlockStatusEffects(arg1) {
  return window['go']['main']['App']['ToggleBlockStatusEffects'](arg1);
}
