// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddChatLog(arg1) {
  return window['go']['main']['App']['AddChatLog'](arg1);
}

export function AddDebugLog(arg1, arg2) {
  return window['go']['main']['App']['AddDebugLog'](arg1, arg2);
}

export function AddErrorLog(arg1, arg2) {
  return window['go']['main']['App']['AddErrorLog'](arg1, arg2);
}

export function AddLogMsg(arg1) {
  return window['go']['main']['App']['AddLogMsg'](arg1);
}

export function AddManualRaffleEntry(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddManualRaffleEntry'](arg1, arg2, arg3);
}

export function AddRaffleEntryFromTrade(arg1, arg2) {
  return window['go']['main']['App']['AddRaffleEntryFromTrade'](arg1, arg2);
}

export function BuildCasinoStats(arg1) {
  return window['go']['main']['App']['BuildCasinoStats'](arg1);
}

export function ClearGameHistory() {
  return window['go']['main']['App']['ClearGameHistory']();
}

export function ClearTradeItems() {
  return window['go']['main']['App']['ClearTradeItems']();
}

export function CreateRaffle(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateRaffle'](arg1, arg2, arg3);
}

export function DeleteRaffle(arg1) {
  return window['go']['main']['App']['DeleteRaffle'](arg1);
}

export function DrawRaffleWinner(arg1) {
  return window['go']['main']['App']['DrawRaffleWinner'](arg1);
}

export function EndRaffle(arg1) {
  return window['go']['main']['App']['EndRaffle'](arg1);
}

export function ExportEventsForDate(arg1) {
  return window['go']['main']['App']['ExportEventsForDate'](arg1);
}

export function GetAutoShoutConfig() {
  return window['go']['main']['App']['GetAutoShoutConfig']();
}

export function GetAutoShoutConfig2() {
  return window['go']['main']['App']['GetAutoShoutConfig2']();
}

export function GetBlockArticlesPageConfig() {
  return window['go']['main']['App']['GetBlockArticlesPageConfig']();
}

export function GetBlockCalendarEventsConfig() {
  return window['go']['main']['App']['GetBlockCalendarEventsConfig']();
}

export function GetBlockFavouriteRoomResultsConfig() {
  return window['go']['main']['App']['GetBlockFavouriteRoomResultsConfig']();
}

export function GetBlockFriendListUpdateConfig() {
  return window['go']['main']['App']['GetBlockFriendListUpdateConfig']();
}

export function GetBlockFriendListUpdateOutgoingConfig() {
  return window['go']['main']['App']['GetBlockFriendListUpdateOutgoingConfig']();
}

export function GetBlockGetCalendarEventsOutgoingConfig() {
  return window['go']['main']['App']['GetBlockGetCalendarEventsOutgoingConfig']();
}

export function GetBlockGetPageArticlesOutgoingConfig() {
  return window['go']['main']['App']['GetBlockGetPageArticlesOutgoingConfig']();
}

export function GetBlockIncoming4095Config() {
  return window['go']['main']['App']['GetBlockIncoming4095Config']();
}

export function GetBlockPollEventEligibilityOutgoingConfig() {
  return window['go']['main']['App']['GetBlockPollEventEligibilityOutgoingConfig']();
}

export function GetBlockRecommendedRoomsConfig() {
  return window['go']['main']['App']['GetBlockRecommendedRoomsConfig']();
}

export function GetBlockRecommendedRoomsOutgoingConfig() {
  return window['go']['main']['App']['GetBlockRecommendedRoomsOutgoingConfig']();
}

export function GetBlockRemoveBuddyConfig() {
  return window['go']['main']['App']['GetBlockRemoveBuddyConfig']();
}

export function GetBlockSlideObjectBundleConfig() {
  return window['go']['main']['App']['GetBlockSlideObjectBundleConfig']();
}

export function GetBlockSlideObjectBundleOutgoingConfig() {
  return window['go']['main']['App']['GetBlockSlideObjectBundleOutgoingConfig']();
}

export function GetBlockStatusEffectsConfig() {
  return window['go']['main']['App']['GetBlockStatusEffectsConfig']();
}

export function GetBlockUserBannedConfig() {
  return window['go']['main']['App']['GetBlockUserBannedConfig']();
}

export function GetCasinoStatsJSON(arg1) {
  return window['go']['main']['App']['GetCasinoStatsJSON'](arg1);
}

export function GetCatalogItemValue(arg1) {
  return window['go']['main']['App']['GetCatalogItemValue'](arg1);
}

export function GetCatalogNameSet() {
  return window['go']['main']['App']['GetCatalogNameSet']();
}

export function GetCurrentTradeItems() {
  return window['go']['main']['App']['GetCurrentTradeItems']();
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function GetDealerOpenConfig() {
  return window['go']['main']['App']['GetDealerOpenConfig']();
}

export function GetGameHistoryJSON() {
  return window['go']['main']['App']['GetGameHistoryJSON']();
}

export function GetLastTradePartnerName() {
  return window['go']['main']['App']['GetLastTradePartnerName']();
}

export function GetRafflesJSON() {
  return window['go']['main']['App']['GetRafflesJSON']();
}

export function GetRiskEnabled() {
  return window['go']['main']['App']['GetRiskEnabled']();
}

export function GetTradeItemsJSON() {
  return window['go']['main']['App']['GetTradeItemsJSON']();
}

export function ListEventDatesJSON() {
  return window['go']['main']['App']['ListEventDatesJSON']();
}

export function ListEventsForDateJSON(arg1) {
  return window['go']['main']['App']['ListEventsForDateJSON'](arg1);
}

export function LoadCatalog() {
  return window['go']['main']['App']['LoadCatalog']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function OpenLastTrade() {
  return window['go']['main']['App']['OpenLastTrade']();
}

export function PauseCasinoSetup() {
  return window['go']['main']['App']['PauseCasinoSetup']();
}

export function ReadEventFileJSON(arg1, arg2) {
  return window['go']['main']['App']['ReadEventFileJSON'](arg1, arg2);
}

export function ResumeCasinoSetup() {
  return window['go']['main']['App']['ResumeCasinoSetup']();
}

export function ResumeRaffle(arg1) {
  return window['go']['main']['App']['ResumeRaffle'](arg1);
}

export function SaveAutoShoutConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveAutoShoutConfig'](arg1, arg2);
}

export function SaveAutoShoutConfig2(arg1, arg2) {
  return window['go']['main']['App']['SaveAutoShoutConfig2'](arg1, arg2);
}

export function SaveCatalog(arg1) {
  return window['go']['main']['App']['SaveCatalog'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveDealerOpenConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveDealerOpenConfig'](arg1, arg2, arg3);
}

export function SetOnlyUnderOver(arg1) {
  return window['go']['main']['App']['SetOnlyUnderOver'](arg1);
}

export function SetRiskEnabled(arg1) {
  return window['go']['main']['App']['SetRiskEnabled'](arg1);
}

export function SetUnderOver7Mode(arg1) {
  return window['go']['main']['App']['SetUnderOver7Mode'](arg1);
}

export function SetUnderOver7PayoutMultiplier(arg1) {
  return window['go']['main']['App']['SetUnderOver7PayoutMultiplier'](arg1);
}

export function ShowCommands() {
  return window['go']['main']['App']['ShowCommands']();
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function SkipDiceSetupForTesting() {
  return window['go']['main']['App']['SkipDiceSetupForTesting']();
}

export function StartCasinoSetup(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartCasinoSetup'](arg1, arg2, arg3, arg4, arg5);
}

export function StartRaffle(arg1) {
  return window['go']['main']['App']['StartRaffle'](arg1);
}

export function StopCasinoSetup() {
  return window['go']['main']['App']['StopCasinoSetup']();
}

export function ToggleAutoShout(arg1) {
  return window['go']['main']['App']['ToggleAutoShout'](arg1);
}

export function ToggleAutoShout2(arg1) {
  return window['go']['main']['App']['ToggleAutoShout2'](arg1);
}

export function ToggleBlockArticlesPage(arg1) {
  return window['go']['main']['App']['ToggleBlockArticlesPage'](arg1);
}

export function ToggleBlockCalendarEvents(arg1) {
  return window['go']['main']['App']['ToggleBlockCalendarEvents'](arg1);
}

export function ToggleBlockFavouriteRoomResults(arg1) {
  return window['go']['main']['App']['ToggleBlockFavouriteRoomResults'](arg1);
}

export function ToggleBlockFriendListUpdate(arg1) {
  return window['go']['main']['App']['ToggleBlockFriendListUpdate'](arg1);
}

export function ToggleBlockFriendListUpdateOutgoing(arg1) {
  return window['go']['main']['App']['ToggleBlockFriendListUpdateOutgoing'](arg1);
}

export function ToggleBlockGetCalendarEventsOutgoing(arg1) {
  return window['go']['main']['App']['ToggleBlockGetCalendarEventsOutgoing'](arg1);
}

export function ToggleBlockGetPageArticlesOutgoing(arg1) {
  return window['go']['main']['App']['ToggleBlockGetPageArticlesOutgoing'](arg1);
}

export function ToggleBlockIncoming4095(arg1) {
  return window['go']['main']['App']['ToggleBlockIncoming4095'](arg1);
}

export function ToggleBlockPollEventEligibilityOutgoing(arg1) {
  return window['go']['main']['App']['ToggleBlockPollEventEligibilityOutgoing'](arg1);
}

export function ToggleBlockRecommendedRooms(arg1) {
  return window['go']['main']['App']['ToggleBlockRecommendedRooms'](arg1);
}

export function ToggleBlockRecommendedRoomsOutgoing(arg1) {
  return window['go']['main']['App']['ToggleBlockRecommendedRoomsOutgoing'](arg1);
}

export function ToggleBlockRemoveBuddy(arg1) {
  return window['go']['main']['App']['ToggleBlockRemoveBuddy'](arg1);
}

export function ToggleBlockSlideObjectBundle(arg1) {
  return window['go']['main']['App']['ToggleBlockSlideObjectBundle'](arg1);
}

export function ToggleBlockSlideObjectBundleOutgoing(arg1) {
  return window['go']['main']['App']['ToggleBlockSlideObjectBundleOutgoing'](arg1);
}

export function ToggleBlockStatusEffects(arg1) {
  return window['go']['main']['App']['ToggleBlockStatusEffects'](arg1);
}

export function ToggleBlockUserBanned(arg1) {
  return window['go']['main']['App']['ToggleBlockUserBanned'](arg1);
}
