// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddChatLog(arg1:string):Promise<void>;

export function AddDebugLog(arg1:string,arg2:Array<any>):Promise<void>;

export function AddErrorLog(arg1:string,arg2:Error):Promise<void>;

export function AddLogMsg(arg1:string):Promise<void>;

export function BuildCasinoStats(arg1:string):Promise<main.CasinoStats>;

export function ClearGameHistory():Promise<void>;

export function ClearTradeItems():Promise<void>;

export function ExportEventsForDate(arg1:string):Promise<string>;

export function GetAutoShoutConfig():Promise<main.AutoShoutConfig>;

export function GetBlockArticlesPageConfig():Promise<main.BlockSlideObjectConfig>;

export function GetBlockCalendarEventsConfig():Promise<main.BlockSlideObjectConfig>;

export function GetBlockFavouriteRoomResultsConfig():Promise<main.BlockSlideObjectConfig>;

export function GetBlockFriendListUpdateConfig():Promise<main.BlockSlideObjectConfig>;

export function GetBlockFriendListUpdateOutgoingConfig():Promise<main.BlockSlideObjectConfig>;

export function GetBlockGetCalendarEventsOutgoingConfig():Promise<main.BlockSlideObjectConfig>;

export function GetBlockGetPageArticlesOutgoingConfig():Promise<main.BlockSlideObjectConfig>;

export function GetBlockIncoming4095Config():Promise<main.BlockSlideObjectConfig>;

export function GetBlockPollEventEligibilityOutgoingConfig():Promise<main.BlockSlideObjectConfig>;

export function GetBlockRecommendedRoomsConfig():Promise<main.BlockRecommendedConfig>;

export function GetBlockRecommendedRoomsOutgoingConfig():Promise<main.BlockRecommendedConfig>;

export function GetBlockRemoveBuddyConfig():Promise<main.BlockSlideObjectConfig>;

export function GetBlockSlideObjectBundleConfig():Promise<main.BlockSlideObjectConfig>;

export function GetBlockSlideObjectBundleOutgoingConfig():Promise<main.BlockSlideObjectConfig>;

export function GetBlockStatusEffectsConfig():Promise<main.BlockSlideObjectConfig>;

export function GetBlockUserBannedConfig():Promise<main.BlockSlideObjectConfig>;

export function GetCasinoStatsJSON(arg1:string):Promise<string>;

export function GetCatalogItemValue(arg1:string):Promise<number|boolean>;

export function GetCatalogNameSet():Promise<Record<string, any>>;

export function GetCurrentTradeItems():Promise<Array<main.TradeItem>>;

export function GetCurrentVersion():Promise<string>;

export function GetDealerOpenConfig():Promise<main.DealerOpenConfig>;

export function GetGameHistoryJSON():Promise<string>;

export function GetLastTradePartnerName():Promise<string>;

export function GetTradeItemsJSON():Promise<string>;

export function ListEventDatesJSON():Promise<string>;

export function ListEventsForDateJSON(arg1:string):Promise<string>;

export function LoadCatalog():Promise<Array<main.CatalogItem>>;

export function LoadConfig():Promise<main.PokerDisplayConfig>;

export function OpenLastTrade():Promise<void>;

export function PauseCasinoSetup():Promise<void>;

export function ReadEventFileJSON(arg1:string,arg2:string):Promise<string>;

export function ResumeCasinoSetup():Promise<void>;

export function SaveAutoShoutConfig(arg1:string,arg2:number):Promise<main.AutoShoutConfig>;

export function SaveCatalog(arg1:Array<main.CatalogItem>):Promise<void>;

export function SaveConfig(arg1:main.PokerDisplayConfig):Promise<void>;

export function SaveDealerOpenConfig(arg1:boolean,arg2:number,arg3:number):Promise<main.DealerOpenConfig>;

export function ShowCommands():Promise<void>;

export function ShowWindow():Promise<void>;

export function SkipDiceSetupForTesting():Promise<void>;

export function StartCasinoSetup(arg1:string,arg2:string,arg3:number,arg4:number):Promise<void>;

export function StartPingPong():Promise<void>;

export function StopCasinoSetup():Promise<void>;

export function StopPingPong():Promise<void>;

export function ToggleAutoShout(arg1:boolean):Promise<main.AutoShoutConfig>;

export function ToggleBlockArticlesPage(arg1:boolean):Promise<main.BlockSlideObjectConfig>;

export function ToggleBlockCalendarEvents(arg1:boolean):Promise<main.BlockSlideObjectConfig>;

export function ToggleBlockFavouriteRoomResults(arg1:boolean):Promise<main.BlockSlideObjectConfig>;

export function ToggleBlockFriendListUpdate(arg1:boolean):Promise<main.BlockSlideObjectConfig>;

export function ToggleBlockFriendListUpdateOutgoing(arg1:boolean):Promise<main.BlockSlideObjectConfig>;

export function ToggleBlockGetCalendarEventsOutgoing(arg1:boolean):Promise<main.BlockSlideObjectConfig>;

export function ToggleBlockGetPageArticlesOutgoing(arg1:boolean):Promise<main.BlockSlideObjectConfig>;

export function ToggleBlockIncoming4095(arg1:boolean):Promise<main.BlockSlideObjectConfig>;

export function ToggleBlockPollEventEligibilityOutgoing(arg1:boolean):Promise<main.BlockSlideObjectConfig>;

export function ToggleBlockRecommendedRooms(arg1:boolean):Promise<main.BlockRecommendedConfig>;

export function ToggleBlockRecommendedRoomsOutgoing(arg1:boolean):Promise<main.BlockRecommendedConfig>;

export function ToggleBlockRemoveBuddy(arg1:boolean):Promise<main.BlockSlideObjectConfig>;

export function ToggleBlockSlideObjectBundle(arg1:boolean):Promise<main.BlockSlideObjectConfig>;

export function ToggleBlockSlideObjectBundleOutgoing(arg1:boolean):Promise<main.BlockSlideObjectConfig>;

export function ToggleBlockStatusEffects(arg1:boolean):Promise<main.BlockSlideObjectConfig>;

export function ToggleBlockUserBanned(arg1:boolean):Promise<main.BlockSlideObjectConfig>;
